server:
  port: 8000
spring:
  application:
    name: microservice-provider-user    # 项目名称尽量用小写
  jpa:
      generate-ddl: false
      show-sql: false
      hibernate:
        ddl-auto: none
  datasource:                           # 指定数据源
    name: DAQ
#     url: jdbc:mysql://106.12.93.249:13306/app?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    url: jdbc:mysql://127.0.0.1:3306/app?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=true
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.0.93:13365/data_import?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
#    username: data_import
#    password: itVfcUXGFNDNiSbRx(59@JsLZ
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    MapUnderscoreToCamelCase: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 192.168.0.39
    database: 44
    port: 15818
    timeout: 100000
    password: Redis1231123@#@!!=-23Sdasd1231gjoiuq123#@sda2131-sadas213dsada@#^%&13asdad3412452332
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
